## makeCacheMatrix and cachesolve are functions that should be used in 
## combination with one another to create and access a list containing 
## the matrix and its inverse. Please note, this program may not be able to
## calculate all inverse matrices.  It can only do the ones supported by solve().

## makeCacheMatrix creates a list containing the input_matrix and an inverse 
## matrix, with initial setting of NULL.  The makeCacheMatrix list also provides
## the ability to set the matrix to something new, and set the inverse to the 
## something new (i.e. the inverse generated by cachesolve)
makeCacheMatrix <- function(input_matrix = matrix()) {
  inverse <- NULL
  set_matrix <- function(new_matrix) {
    input_matrix <<- new_matrix
    inverse <<- NULL
  }
  set_inverse <- function(inverse_set) inverse <<- inverse_set
  get_inverse <- function() inverse
  list(set = set_matrix, get = input_matrix, setinverse = set_inverse,
       getinverse = get_inverse)
}

## cacheSolve can be used in two situations.  1, to generate the inverse matrix
## for the matrix stored in the list generated by makeCacheMatrix, and 2, to 
## retrieve the stored inverse matrix, previously generated with cacheSolve.
## This progam informs the user if the data has been cached before.
cacheSolve <- function(x, ...) {
  inverse <- x$getinverse()
  if(!is.null(inverse)) {
    message("getting cached data")
    return(inverse)
  }
  else { message("generating inverse and caching data")}
  data <- x$get
  inverse <- solve(data)
  x$setinverse(inverse)
  inverse
} 
